name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.12']

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
          ~/.cache/coverage
          ~/.cache/mypy
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Safety scan
      run: |
        pip install safety
        safety check -r requirements.txt --full-report

    - name: Run tests
      run: pytest -q
      env:
        SLOW_TESTS: "1"

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files

  build-wheel:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
            ~/.cache/coverage
            ~/.cache/mypy
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build module
        run: |
          pip install --upgrade pip
          pip install build

      - name: Build wheel
        run: python -m build --wheel

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dist
          path: dist/*.whl
